#!/bin/bash
in_ext=${1:-md}
out_ext=${2:-pdf}
for in_file in *.$in_ext; do
  out_file=${in_file%%.*}.$out_ext
done 

makeit="make EXT=$in_ext $out_ext"
eval $makeit
rifle $out_file
echo $in_file | entr sh -c "reset && eval $makeit && count $out_file"
